### PR TITLE
Mint cleanup and Escapeshellarg improvement

### PR DESCRIPTION
**Pull request by pocomane**

### CODE REVIEW

**Comment by pocomane** [comment]
I do not already know how to change the garbage-collection tests to be reproducible. Moreover it seems that luajit table.unpack stops at first nil.

Both issues need a bit of development.

**Comment by aiq** [comment]
I dont check the function name intern?

**Comment by pocomane** [comment]
I chose "Intern" as in "Interning string" (e.g. java String.Intern()) . However feel free to chage it to a better name.

You can avoid to work on (and merge) both intern and tuple until I fix the test failures.

**Comment by pocomane** [comment]
Well, at least, now, it is only a problem of stocastic test failing :)

However, I have no clue: I can not repoduce the test failure on my machine, neither launching it thousand of times :(

Note that the fix in the last commit (30551cb) was not involved in all this situation. The failure is just due to the inability in the test files to wait until the GC completely free the unused object. Maybe the GC test can be just skipped ? 

```
...

local skip = function() return true end

local gccount = 0
local x = int( true, false )
x = setmetatable( x, {__gc=function(t) gccount = gccount + 1 end} )

-- No collection if some reference is still around
collectgarbage('collect')
t( gccount, 0, skip )

-- Automatic collection
x = nil
collectgarbage('collect')
t( gccount, 1, skip )

...
```

**Comment by pocomane** [comment]
I skipped the gc tests for lua versions that do not provide the __gc metamethod.

The gc tests became a bit bloated. Maybe they can be moved to a new .ex2 file not included in the documentation ?

**Comment by aiq** [comment]
The moving to a second test/example file is totally fine. But all examples test should be included into the documentation.
I hope that I find some time before eastern to merge your code. I will change the name of intern to flyweight and move this function into the arr directory.

Thanks for your work.

**Comment by aiq** [comment]
Thanks.
Some Nodes to the changes after the merge. 
* flyweightstore is a long name but intern was to abstract for me
* flyweightstore is in the tab directory, because it handles special tables that are not array like tables

**Pull request merged**
